### ISSUE TITLE
Current error.py is not friendly or scalable

### ISSUE THREAD

**Issue by pybash1** [Morgan-Phoenix/EnroCrypt#7]
The current error.py file contains a class which contains several functions for raising an error. This is not a very good practice. Also, you are using the cryptography library to get a error. Instead just create different classes for each exception and create your own exception instead of importing from cryptography for starting this is fine but after that not. To learn more about it refer [here](https://www.programiz.com/python-programming/user-defined-exception#:~:text=serve%20your%20purpose.-,Creating%20Custom%20Exceptions,the%20built%2Din%20Exception%20class.) And [here](https://docs.python.org/3/library/exceptions.html) and [here](https://docs.python.org/3/tutorial/errors.html). **If you feel like I am being to rude or bossy sorry, I like this library and am just highlighting a few issues which when fixed would make the library great.**

**Comment by Morgan-Phoenix** [comment]
I'll do so tomorrow and don't think that in the end of the day

**Comment by Morgan-Phoenix** [comment]
I have Made Changes,
Hope U Like It :-)

**Comment by pybash1** [comment]
yes that is way better..
